### ISSUE TITLE
tracking: Sync Repos

### ISSUE THREAD

**Issue by HurricanKai** [windmill-labs/windmill#1182]
Updates still required for sync repos:

- Convert to templates
  - Add docs to readmes on how to setup
  - Should we split into template & demo repos? (.wmill folder?)
  - Can use the "use this template" button from https://buttons.github.io/
- Update to use webhook
- Last pass to verify everything works as intended

**Comment by rubenfiszel** [comment]
CLI sync todo:

- [ ] 1. sync entire workspace
- [ ] 2. sync add folders
- [ ] -- workspace add
- [ ] 4. remote should  default https://app.windmill.dev/
- [ ] 5. Also it should ask the id first and then provide as default the id for the name
- [ ] 6.  is there a way to xdg-open the browser, also, if there is a way to make that a clickable link in the terminal
- [ ] 7. Improve LongLink handling
- [ ] 8. have a A for yes to all, or similar
- [ ] 9. wmill without args should display help
- [ ] 10. help should suggest to add a workspace if there are no workspace
- [ ] 11. help should mention you can ask for help even for subcommands
- [ ] 12. wmill sync -h should mention the --raw options and link to docs
- [ ] 13. wmill sync -h should give a brief overview that one need to add files for them to be tracked, and explain the lifecycle between init, add, pull, push
